spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:jobpulsedb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    database: H2
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: debug
    org.springframework.web: debug
    ru.jobpulse: debug
    org.hibernate.sql: debug

liquibase:
  drop-first: ${LIQUIBASE_DROP_FIRST:true}