spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/jobpulse}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    drop-first: ${LIQUIBASE_DROP_FIRST:false}

hh:
  api-url: https://api.hh.ru

logging:
  level:
    root: info
    ru.jobpulse: info

security:
  jwt:
    expiration-time: 3600000
    secret-key: "cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"