spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/jobpulse}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    drop-first: ${LIQUIBASE_DROP_FIRST:false}

hh:
  api-url: https://api.hh.ru

logging:
  level:
    root: info
    ru.jobpulse: info